import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  FootnoteReferenceRun,
} from 'docx';
import { saveAs } from 'file-saver';

const CAVEAT_1 = 'The corpus is a curated subset of Indian Standards, not the complete published universe.';
const CAVEAT_2 =
  "Version/amendment info reflects the corpus snapshot and is not live-verified against BIS's current register — users must verify before finalising a tender.";

const UNVERIFIED_NOTE =
  'Certification status was not verified for this entry — confirm the correct certification requirement with BIS before the tender is issued.';

function todayStamp() {
  return new Date().toISOString().slice(0, 10);
}

function buildSummary(tender) {
  let totalStandards = 0;
  let unverified = 0;
  for (const item of tender.items) {
    totalStandards += item.standards.length;
    unverified += item.standards.filter((s) => s.certificationBadge === 'Not determined').length;
  }
  return { totalItems: tender.items.length, totalStandards, unverified };
}

function provenanceText(standard) {
  if (standard.provenance === 'allied') {
    return `Auto-added (allied reference via ${standard.sourceStandardNumber}${
      standard.relationshipType ? `, ${standard.relationshipType}` : ''
    })`;
  }
  return 'User-added';
}

export async function exportTenderToDocx(tender) {
  const { totalItems, totalStandards, unverified } = buildSummary(tender);
  const footnotes = {};
  let footnoteId = 0;

  const itemBlocks = tender.items.flatMap((item) => {
    const headerRow = new TableRow({
      children: ['Standard', 'Title', 'Certification', 'Provenance'].map(
        (text) =>
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text, bold: true })] })],
          })
      ),
    });

    const rows = item.standards.map((s) => {
      const certRunChildren = [new TextRun(s.certificationBadge ?? '—')];
      if (s.certificationBadge === 'Not determined') {
        footnoteId += 1;
        footnotes[footnoteId] = {
          children: [new Paragraph({ children: [new TextRun(UNVERIFIED_NOTE)] })],
        };
        certRunChildren.push(new FootnoteReferenceRun(footnoteId));
      }

      return new TableRow({
        children: [
          new TableCell({ children: [new Paragraph(s.standardNumber)] }),
          new TableCell({ children: [new Paragraph(s.title ?? '—')] }),
          new TableCell({ children: [new Paragraph({ children: certRunChildren })] }),
          new TableCell({ children: [new Paragraph(provenanceText(s))] }),
        ],
      });
    });

    return [
      new Paragraph({ text: item.name, heading: HeadingLevel.HEADING_2 }),
      new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [headerRow, ...rows] }),
      new Paragraph({ text: '' }),
    ];
  });

  const doc = new Document({
    footnotes,
    sections: [
      {
        children: [
          new Paragraph({ text: 'ManakMitra — Tender Standards Export', heading: HeadingLevel.TITLE }),
          new Paragraph({ text: `Generated ${todayStamp()}` }),
          new Paragraph({ text: 'Generated by ManakMitra (unofficial, built for SIH 2026)' }),

          new Paragraph({ text: 'Methodological caveats', heading: HeadingLevel.HEADING_2 }),
          new Paragraph({ text: CAVEAT_1 }),
          new Paragraph({ text: CAVEAT_2 }),

          new Paragraph({ text: 'Summary', heading: HeadingLevel.HEADING_2 }),
          new Paragraph({
            text: `${totalItems} item(s) · ${totalStandards} standard(s) total · ${unverified} with unverified certification.`,
          }),

          ...itemBlocks,
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `ManakMitra-tender-${todayStamp()}.docx`);
}

function csvField(value) {
  const str = String(value ?? '');
  return /[",\n]/.test(str) ? `"${str.replace(/"/g, '""')}"` : str;
}

export function exportTenderToCsv(tender) {
  const header = [
    'Tender Item',
    'Standard Number',
    'Title',
    'Certification',
    'Confidence Band',
    'Category',
    'Provenance',
    'Relationship Type',
  ];
  const rows = [header];
  for (const item of tender.items) {
    for (const s of item.standards) {
      rows.push([
        item.name,
        s.standardNumber,
        s.title ?? '',
        s.certificationBadge ?? '',
        s.confidenceBand ?? '',
        s.category ?? '',
        s.provenance === 'allied' ? 'Auto-added (allied)' : 'User-added',
        s.relationshipType ?? '',
      ]);
    }
  }

  const csv = rows.map((row) => row.map(csvField).join(',')).join('\r\n');
  // BOM so Excel reliably detects UTF-8 rather than guessing a local codepage.
  const blob = new Blob(['﻿' + csv], { type: 'text/csv;charset=utf-8;' });
  saveAs(blob, `ManakMitra-tender-${todayStamp()}.csv`);
}
